version: "3.8"

services:
  db:
    image: postgres:12.3
    container_name: liveman_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=liveman_dev
    ports:
      - "5432:5432"

  livebook:
    image: livebook/livebook:0.2.0
    container_name: liveman_livebook
    environment:
      - LIVEBOOK_PASSWORD=livemanisawesome
      - LIVEBOOK_DEFAULT_RUNTIME=mix:/data/liveman
    ports:
      - "8080:8080"
    volumes:
      - .:/data
