name: Deploy

on:
  push:
    branches:
      - develop
      - main

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Heroku Container registry
        run: heroku container:login

      - name: Build and push
        run: heroku container:push -a $HEROKU_APP_NAME web

      - name: Release
        run: heroku container:release -a $HEROKU_APP_NAME web
