name: Publish Liveman Docker Image

on:
  push:
    branches:
      - main

env:
  # TODO: Find a way to automatically retrieve version from mix
  VERSION: "0.1.0"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./liveman_api
          push: true
          tags: $DOCKER_IMAGE:$VERSION
          cache-from: type=registry,ref=$DOCKER_IMAGE:latest
          cache-to: type=inline
